### ISSUE TITLE
Hi, does anyone know how to deploy this?  I try to deploy through the remix, but every time I get an error (code: -32000, message: "execution reverted") Does anyone know what to do with this?  Thank you!

### ISSUE THREAD

**Issue by bipolaraius** [FreezyEx/Pandamoon-Token#1]

**Comment by FreezyEx** [comment]
Check for router address. If you are on testnet you must use this: 0xD99D1c33F9fC3444f8101754aBC46c52416550D1
if you are on mainnet use this: 0x10ED43C718714eb63d5aA57B78B54704E256024E
